---
title: "Eight Schools"
output: html_notebook
---

```{r setup}
library(outbreaks)
library(rstan)
library(tidyverse)
library(rstansim)
options(mc.cores = 8)
rstan_options(auto_write = TRUE)
```

Note: https://ewan-keith.github.io/rstansim/articles/using-rstansim.html provides a helpful guide.

```{r}
model <- stan_model("champagne2022.stan")

years = 365.25
annual_subdivisions = 12
max_time = 1 * years
t0 = -0 * years
t = seq(years/annual_subdivisions, max_time, annual_subdivisions)
n_times = length(t)
# time series of cases
# cases = rep(100, n_times) + round(rnorm(n_times, 0, 10))
cases = round(rnorm(n_times, 100, 10))
N = 1000;

#initial conditions
I_init = 0.1
y0 = c(Il=0, I0=I_init, Sl=0, S0=1-I_init, Infections=0)

# data for Stan
data <- list(n_times = n_times, y0 = y0, t0 = t0, ts = t, N = N, cases = cases,
                 r = 1./60, # r
                 gammal = 1./223, # gammal
                 f = 1./72, # f
                 alpha = 0.21, # alpha
                 beta = 0.66, # beta
                 rho = 0.21, # rho
                 delta = 0
)

# number of MCMC steps
niter <- 10000
```

```{r}
# Generate data
synth_data = simulate_data("champagne2022.stan", data_name="dummy_data", input_data=data,
                           param_values=list(lambda=0.01, phi_inv=0.001))

synth_data = readRDS("dummy_data_1.rds")

synth_df = synth_data[names(synth_data)[sapply(synth_data, function(x) {length(x) == n_times})]] %>%
  lapply(function(x) {x[seq_len(n_times-1)]}) %>%
  as_tibble()

ggplot(synth_df, aes(x=ts, y=cases)) +
  geom_point()
```

```{r}
# Find maximum likelihood for good starting parameters
optim = optimizing(model, data = data, hessian = FALSE)

plot_data = optim$par %>%
  as.data.frame() %>%
  bind_cols(rownames(.), .) %>%
  setNames(c("name", "value")) %>%
  as_tibble() %>%
  mutate(index_i = name %>% str_extract("(?<=\\[)[0-9]+") %>% as.numeric(),
         time = t[index_i],
         index_j = name %>% str_extract("(?<=,)[0-9]+") %>% as.numeric(),
         compartment = names(y0)[index_j],
         variable = name %>% str_remove("\\[.*")) %>%
  mutate(variable = coalesce(compartment, variable))

plot_data %>%
  drop_na(time) %>%
  ggplot(aes(x=time, y=value, color=variable, group=variable)) +
  geom_line() +
  facet_wrap(vars(variable), scales="free_y") +
  coord_cartesian(ylim = c(0, NA))
```

```{r}
n_chains = 4
theta_init = as.list(optim$par[c("lambda", "phi_inv")]) # optimisation results
fit_sis_negbin <- sampling(model,
                           data = data,
                           iter = niter,
                           chains = n_chains, 
                           # init = rep(list(theta_init), n_chains),
                           seed = 0)
```

```{r}
pars=c("lambda", "phi_inv")
print(fit_sis_negbin, pars = pars)
stan_dens(fit_sis_negbin, pars = pars, separate_chains = TRUE)

smr_pred <- cbind(as.data.frame(summary(
  fit_sis_negbin, pars = "pred_cases", probs = c(0.05, 0.5, 0.95))$summary),
  t=t[1:(n_times-1)], cases=cases[1:(n_times-1)])
colnames(smr_pred) <- make.names(colnames(smr_pred)) # to remove % in the col names

c_posterior = "blue"
ggplot(smr_pred, mapping = aes(x = t)) +
  geom_ribbon(aes(ymin = X5., ymax = X95.), fill = c_posterior, alpha = 0.35) +
  geom_line(mapping = aes(x = t, y = X50.), color = c_posterior) + 
  geom_point(mapping = aes(y = cases)) +
  labs(x = "Day", y = "Cases") +
  coord_cartesian(ylim = c(0, NA))

params <- c(sapply(seq_along(t), function(i) { sprintf("y[%s,5]", i)} ), #number of infected for each day
            "pred_cases")
smr_y <- as.data.frame(summary(fit_sis_negbin, 
                               pars = params, probs = c(0.05, 0.5, 0.95))$summary) %>%
  bind_cols(rownames(.), .) %>%
  rename(name = 1) %>%
  # filter(name %>% str_starts("y")) %>%
  mutate(index_i = name %>% str_extract("(?<=\\[)[0-9]+") %>% as.numeric(),
         time = t[index_i],
         index_j = name %>% str_extract("(?<=,)[0-9]+") %>% as.numeric(),
         compartment = names(y0)[index_j],
         variable = name %>% str_remove("\\[.*")) %>%
  mutate(variable = coalesce(compartment, variable))

ggplot(smr_y, mapping = aes(x = time)) +
  geom_ribbon(aes(ymin = `5%`, ymax = `95%`, fill=variable), alpha = 0.35) +
  geom_line(mapping = aes(y = `50%`, color=variable)) + 
  labs(x = "Day", y = "True incidence") +
  coord_cartesian(ylim = c(0, NA))
```

```{r}
plot_data = summary(fit_sis_negbin)$summary %>%
  bind_cols(name = rownames(.), .) %>%
  mutate(index_i = name %>% str_extract("(?<=\\[)[0-9]+") %>% as.numeric(),
         time = t[index_i],
         index_j = name %>% str_extract("(?<=,)[0-9]+") %>% as.numeric(),
         compartment = names(y0)[index_j],
         variable = name %>% str_remove("\\[.*")) %>%
  mutate(variable = coalesce(compartment, variable))

plot_data %>%
  drop_na(time) %>%
  ggplot(aes(x=time, y=mean, color=variable, group=variable)) +
  geom_ribbon(aes(ymin = `25%`, ymax = `75%`, fill=variable, color=NULL), alpha=0.5) +
  geom_line() +
  facet_wrap(vars(variable), scales="free_y")

pairs(fit_sis_negbin, pars=pars)
```

```{r}
model2 <- stan_model("champagne2022_generation.stan")
data_generate <- list(n_times = n_times, y0 = y0, t0 = t0, ts = t, N = N,
                          r = 1./60, # r
                          gammal = 1./223, # gammal
                          f = 1./72, # f
                          alpha = 0.21, # alpha
                          beta = 0.66, # beta
                          rho = 0.21, # rho
                          delta = 0,
                          lambda = 0.01,
                          phi_inv = 0.0001
)
# x = generate_quantities(

predictions = stan(file = "champagne2022_generation.stan", data = data_generate, chains = 1, iter = 1, algorithm = "Fixed_param")

pred_cases = as.data.frame(predictions)

# Check with R implementation

```
