_---
title: "PLAN for Chapter 1. Methodology for fitting ODE epidemic models"
subtitle: "This RMarkdown is a template as initially outlined in the progress report. Each task will be outlined and then followed by a code block to be completed."
output:
html_notebook:
number_sections: true
---

This is to test a model with variable numbers of compartments.

```{r setup}
library(R.utils)
library(tidyverse)
library(rstan)
library(rstansim) # devtools::install_github("ewan-keith/rstansim")
library(parallel)
library(patchwork)
library(ggrepel)
library(pbmcapply)
library(pbapply)
library(RColorBrewer)
source("../R/load_functions.R")


plot_output = function(output) {
  plot_data = output %>%
    pivot_longer(-time) %>%
    mutate(Type = case_match(name,
                             c("Cases", "ReportedShortIncubations", "Relapses", "ReportedRelapses", "ReportedShortIncubations", "ReportedCases", "ReportedShortIncubations", "ReportedLongIncubations") ~ "Cases",
                             c("Infectious", "Dormant", "Latent", "Susceptible") ~ "Compartment",
                             .default = name)) %>%
    filter(name != "Susceptible",
           Type %in% c("Cases", "Compartment"))
  
  ggplot(plot_data, aes(x=time, y=value, color=name)) +
    geom_line() +
    facet_wrap(vars(Type), ncol=1, scales="free_y")
}
```

```{r}
model_file = "../stan/test_delay_1.stan"
model = stan_model(model_file)

rstan_options(auto_write = TRUE)

n_years = 5
n_iter = 100 # should be at least 500
n_chains = 2
n_repetitions = 1 # how many times to duplicate each scenario
cores_per_sampler = n_chains # 1 for mclapply, or n_chains if not running lots of scenarios
limit_runs = Inf # set to a finite number for testing, or Inf to run all
timelimit_per_run = 60*60 * 5
n_traces = 200 # limit for plotting sample trajectories

n_times = 100
n_delays = 4
data = list(
  `T` = n_times,
  t0 = 0,
  ts = 1:n_times,
  n_delays = n_delays,
  cases = rep(5, n_times),
  y0 = c(1, rep(0, n_delays)),
  dummy = 10
)

true_params = list(
  sigma = 1,
  alpha = 0.1
)

sim_list = my_simulate_data_list(
  file = model_file,
  data_name = "test",
  input_data = data,
  vars = "all",
  param_values = true_params
)

y = sim_list$y %>%
  as_tibble()

y %>%
  mutate(t = sim_list$ts) %>%
  pivot_longer(-t) %>%
  ggplot(aes(x = t, y = value, color= name)) +
  geom_line()

# fit = sampling(
#   model,
#   data = data
# )
```

```{r}
# Initialise values for verification runs
n_times = 365*10
data_null = list(
  n_times = n_times,
  t0 = 0,
  ts = 1:n_times,
  cases = rpois(n_times, 100),
  alpha = 1,
  beta = 1,
  relapse_clinical_immunity = 0,
  gamma_d = 1/434.,
  gamma_l = 1/223,
  delta = 1/162,
  phi = 0,
  f = 1/72,
  r = 1/60,
  p_long = 0,
  p_silent = 0,
  population_size = 1,
  
  n_dormant = 11,
  eps = 1,
  kappa = 1,
  phase = 0,
  
  run_estimation = 0
)
# model_file = "../stan/test_delay_2.stan"
# model = stan_model(model_file)
model_file = "../stan/test_delay_3.stan"
model = stan_model(model_file)
```

```{r short_relapse}
n_times = 365*2
ts = 1:n_times
cases = rpois(n_times, 100)
data = data_init(data_null,
                 n_times = n_times,
                 ts = ts,
                 cases = cases,
                 gamma_l = 0,
                 gamma_d = 0)
data$y0 = state_init(data, list(1) %>% setNames(paste0("Sl", data$n_dormant+1)))

true_params = list(lambda = 0.0)

sim_out = sampling(model, data = data, chains = 1, iter = 1)
sim_summary = extract_summary(data, sim_out)

plot_output(sim_summary)
```

```{r long_relapse}
n_times = 365*2
ts = 1:n_times
cases = rpois(n_times, 100)
data = data_init(data_null,
                 n_times = n_times,
                 ts = ts,
                 cases = cases,
                 gamma_l = 0,
                 gamma_d = 0,
                 f = 2)
data$y0 = state_init(data, Sl1=1)

true_params = list(lambda = 0.0)

sim_out = sampling(model, data = data, chains = 1, iter = 1)
sim_summary = extract_summary(data, sim_out)

plot_output(sim_summary)

plot_data = sim_summary %>%
  select(-matches("True|Reported|Dormant|Prevalence|Infectious|Latent|Susceptible")) %>%
  pivot_longer(-time, names_to="Compartment", values_to="Proportion")
plot_labels = plot_data %>%
  group_by(Compartment) %>%
  arrange(desc(Proportion)) %>%
  slice(1) %>%
  filter(Proportion > 0)

ggplot(plot_data, aes(x=time, y=Proportion, color=Compartment)) +
  geom_line() +
  geom_text_repel(data=plot_labels, aes(label=Compartment), direction="y", nudge_x=5, max.overlaps=1e6) +
  theme(legend.position = "none") +
  labs(subtitle = "Begin with long-relapse hypnozoites, instant latent relapse, and complete treatment")
```

```{r all_stages_relapse}
# Under contrived situations (zero transmission, zero natural clearance, 100\% ascertainment), the measured mean and variance of long-delay relapses is within 1\% of theory (Erlang distribution plus exponential).

n_times = 365*2
ts = 1:n_times
cases = rpois(n_times, 100)
data = data_init(data_null,
                 n_times = n_times,
                 ts = ts,
                 cases = cases,
                 gamma_l = 0,
                 gamma_d = 0)
data$y0 = state_init(data, Sl1=1)

true_params = list(lambda = 0.0)

sim_out = sampling(model, data = data, chains = 1, iter = 1)
sim_summary = extract_summary(data, sim_out)

plot_output(sim_summary)

plot_data = sim_summary %>%
  select(-matches("True|Reported|Dormant|Prevalence|Infectious|Latent|Susceptible")) %>%
  pivot_longer(-time, names_to="Compartment", values_to="Proportion")
plot_labels = plot_data %>%
  group_by(Compartment) %>%
  arrange(desc(Proportion)) %>%
  slice(1) %>%
  filter(Proportion > 0)

ggplot(plot_data, aes(x=time, y=Proportion, color=Compartment)) +
  geom_line() +
  geom_text_repel(data=plot_labels, aes(label=Compartment), direction="y", nudge_x=5, max.overlaps=1e6) +
  theme(legend.position = "none") +
  labs(subtitle = "Begin with long-relapse hypnozoites, normal latent relapse, and complete treatment")
```

```{r continuous_transmission}
data = data_init(data_null,
                 alpha = 0.5,
                 p_silent = 0, # this is unrelated
                 p_long = 1, # something about p_long>0 makes it lose summation to 1
                 gamma_l = 0,
                 gamma_d = 0,
                 r = 0,
                 f = 0,
                 n_dormant = 3,
                 relapse_clinical_immunity = 1,
                 delta = 0.1) # people get lost when the long relapse occurs

data$y0 = state_init(data, "Icl1" = 1)
real_params = list(lambda = 1e-12)

sim_out = my_simulate_data_list(
  file = model_file,
  data_name = "dummy_data",
  input_data = data,
  param_values = real_params,
  vars = c("y")
)$y %>%
  as_tibble() %>%
  setNames(names(data$y0)) %>%
  mutate(time = data$ts, .before=0) %>%
  mutate(time = time,
         Infectious = rowSums(across(starts_with("I"))),
         Dormant = rowSums(across(matches(paste0("^Sc?l(", paste(seq_len(data$n_dormant), collapse="|"), ")$")))),
         Latent = rowSums(across(matches(paste0("^Sc?l", data$n_dormant+1, "$")))),
         Susceptible = S0,
         Prevalence = 1 - S0,
         Total = rowSums(across(matches(paste0("^(S|I).{,5}$")))),
         # Below incidence rates are in units of people per day
         across(matches("True"), ~ (lead(.x) - .x) / as.numeric(lead(time) - time)),
         TrueCases = TrueShortIncubations + TrueLongIncubations + TrueRelapses,
         ReportedShortIncubations = TrueShortIncubations * data$alpha,
         ReportedLongIncubations = TrueLongIncubations * data$alpha,
         ReportedRelapses = TrueRelapses * (1-data$relapse_clinical_immunity) * data$alpha,
         ReportedCases = ReportedShortIncubations + ReportedLongIncubations + ReportedRelapses,
         .keep = "used")

# plot_output(sim_out)

plot_data = sim_out %>%
  select(-matches("True|Reported|Dormant|Prevalence|Infectious|Latent|Susceptible")) %>%
  # select(time, Susceptible, Latent, Dormant, Infectious, Total) %>%
  pivot_longer(-time, names_to="Compartment", values_to="Proportion") %>%
  filter(!Compartment %in% c("I0", ""),
         time <= 10)

plot_labels = plot_data %>%
  group_by(Compartment) %>%
  arrange(desc(Proportion)) %>%
  slice(1) %>%
  filter(Proportion > 0)

ggplot(plot_data, aes(x=time, y=Proportion, color=Compartment)) +
  geom_line() +
  geom_text_repel(data=plot_labels, aes(label=Compartment), direction="y", nudge_x=1, max.overlaps=1e6) +
  coord_cartesian(ylim = c(0, 1)) +
  theme(legend.position = "none") +
  labs(subtitle = "Begin with long-relapse hypnozoites, normal latent relapse, and complete treatment")
```

```{r scenario_1}
# Under seasonal transmission short relapses should skew infections; i.e., cause a long tail.
data = data_init(data_null,
                 alpha = 0.93,
                 gamma_l = 0,
                 gamma_d = 0,
                 eps = 0.001,
                 kappa = 1)

data$y0 = state_init(data, "I0" = 0.01)
real_params = list(lambda = 1)

sim_out = my_simulate_data_list(
  file = model_file,
  data_name = "dummy_data",
  input_data = data,
  param_values = real_params,
  vars = c("y")
)$y %>%
  as_tibble() %>%
  setNames(names(data$y0)) %>%
  mutate(time = data$ts, .before=0) %>%
  mutate(time = time,
         Infectious = rowSums(across(starts_with("I"))),
         Dormant = rowSums(across(matches(paste0("^Sc?l(", paste(seq_len(data$n_dormant), collapse="|"), ")$")))),
         Latent = rowSums(across(matches(paste0("^Sc?l", data$n_dormant+1, "$")))),
         Susceptible = S0,
         Prevalence = 1 - S0,
         # Below incidence rates are in units of people per day
         across(matches("True"), ~ (lead(.x) - .x) / as.numeric(lead(time) - time)),
         TrueCases = TrueShortIncubations + TrueLongIncubations + TrueRelapses,
         ReportedShortIncubations = TrueShortIncubations * data$alpha,
         ReportedLongIncubations = TrueLongIncubations * data$alpha,
         ReportedRelapses = TrueRelapses * (1-data$relapse_clinical_immunity) * data$alpha,
         ReportedCases = ReportedShortIncubations + ReportedLongIncubations + ReportedRelapses,
         .keep = "used") %>%
  select(time, ReportedCases, ReportedRelapses, ReportedCases, ReportedShortIncubations)

plot_output(sim_out)
# short relapses skew peak timing late
```


```{r scenario_2}
# Examine effect of p_long
n_times = 365*2
ts = 1:n_times
cases = rpois(n_times, 100)
data = data_init(data_null,
                 n_times = n_times,
                 ts = ts,
                 cases = cases,
                 alpha = 1,
                 beta = 1,
                 p_long = 0,
                 p_silent = 1,
                 gamma_l = 0,
                 gamma_d = 0)
data_1 = data_2 = data_3 = data
data_1$y0 = state_init(data, Sl12 = 1)
data_2$y0 = state_init(data, Sl1 = 0.5, Sl12 = 0.5)
data_3$y0 = state_init(data, Sl1 = 1)
real_params = list(lambda = 1e-12)

sims_out = list(
  `p_long=0` = data_1,
  `p_long=0.5` = data_2,
  `p_long=1` = data_3
) %>%
  lapply(function(x) {
    my_simulate_data_list(
      file = model_file,
      data_name = "dummy_data",
      input_data = x,
      param_values = real_params,
      vars = c("y")
    )$y %>%
      as_tibble() %>%
      setNames(names(x$y0)) %>%
      mutate(time = x$ts, .before=0) %>%
      mutate(time = time,
             Infectious = rowSums(across(starts_with("I"))),
             Dormant = rowSums(across(matches(paste0("^Sc?l(", paste(seq_len(x$n_dormant), collapse="|"), ")$")))),
             Latent = rowSums(across(matches(paste0("^Sc?l", x$n_dormant+1, "$")))),
             Susceptible = S0,
             Prevalence = 1 - S0,
             Total = rowSums(across(matches(paste0("^(S|I).{,5}$")))),
             # Below incidence rates are in units of people per day
             across(matches("True"), ~ (lead(.x) - .x) / as.numeric(lead(time) - time)),
             TrueCases = TrueShortIncubations + TrueLongIncubations + TrueRelapses,
             ReportedShortIncubations = TrueShortIncubations * x$alpha,
             ReportedLongIncubations = TrueLongIncubations * x$alpha,
             ReportedRelapses = TrueRelapses * (1-x$relapse_clinical_immunity) * x$alpha,
             ReportedCases = ReportedShortIncubations + ReportedLongIncubations + ReportedRelapses,
             .keep = "used")
  })

plot_data = sims_out %>% bind_rows(.id = "Var") %>%
  pivot_longer(c(ReportedCases, Infectious, Dormant, Latent, Susceptible, Total)) %>%
  mutate(Type = ifelse(name %in% c("ReportedCases", "Omega"), name, "Compartment"))

ggplot(plot_data, aes(x=time, y=value, color=name)) +
  geom_line() +
  facet_grid(rows=vars(Type), cols=vars(Var), scales="free_y") +
  labs(subtitle = "The proportion beginning in Sl1 vs Sl[n] combines short and long relapse peaks")
```

```{r scenario_3}
# Examine effect of p_silent
n_times = 365*10
ts = 1:n_times
cases = rpois(n_times, 100)
data = data_init(data_null,
                 n_times = n_times,
                 ts = ts,
                 cases = cases,
                 alpha = 0.5,
                 beta = 0.9,
                 p_long = 0.5,
                 eps = 0.001,
                 kappa = 5,
                 phase = 0)
data$y0 = state_init(data, I0 = 0.01)
data_1 = data_2 = data_3 = data
data_1$p_silent = 0
data_2$p_silent = 0.5
data_3$p_silent = 1
real_params = list(lambda = 0.05)

sims_out = list(
  `p_silent=0` = data_1,
  `p_silent=0.5` = data_2,
  `p_silent=1` = data_3
) %>%
  lapply(function(x) {
    my_simulate_data_list(
      file = model_file,
      data_name = "dummy_data",
      input_data = x,
      param_values = real_params,
      vars = c("y")
    )$y %>%
      as_tibble() %>%
      setNames(names(x$y0)) %>%
      mutate(time = x$ts, .before=0) %>%
      mutate(time = time,
             Infectious = rowSums(across(starts_with("I"))),
             Dormant = rowSums(across(matches(paste0("^Sc?l(", paste(seq_len(x$n_dormant), collapse="|"), ")$")))),
             Latent = rowSums(across(matches(paste0("^Sc?l", x$n_dormant+1, "$")))),
             Susceptible = S0,
             Prevalence = 1 - S0,
             Total = rowSums(across(matches(paste0("^(S|I).{,5}$")))),
             # Below incidence rates are in units of people per day
             across(matches("True"), ~ (lead(.x) - .x) / as.numeric(lead(time) - time)),
             TrueCases = TrueShortIncubations + TrueLongIncubations + TrueRelapses,
             ReportedShortIncubations = TrueShortIncubations * x$alpha,
             ReportedLongIncubations = TrueLongIncubations * x$alpha,
             ReportedRelapses = TrueRelapses * (1-x$relapse_clinical_immunity) * x$alpha,
             ReportedCases = ReportedShortIncubations + ReportedLongIncubations + ReportedRelapses,
             .keep = "used")
  })

plot_data = sims_out %>% bind_rows(.id = "Var") %>%
  pivot_longer(c(ReportedCases, Infectious, Dormant, Latent, Total)) %>%
  mutate(Type = ifelse(name %in% c("ReportedCases", "Omega"), name, "Compartment"))

ggplot(plot_data, aes(x=time, y=value, color=name)) +
  geom_line() +
  facet_grid(rows=vars(Type), cols=vars(Var), scales="free_y")

plot_data = sims_out %>% 
  bind_rows(.id = "Var") %>%
  select(-matches("True|Reported|Dormant|Prevalence|Infectious|Latent|Susceptible")) %>%
  pivot_longer(-c(Var, time), names_to="Compartment", values_to="Proportion") %>%
  filter(Compartment %>% str_detect("12"))

plot_labels = plot_data %>%
  group_by(Compartment, Var) %>%
  arrange(desc(Proportion)) %>%
  slice(1) %>%
  filter(Proportion > 0,
         Compartment %>% str_detect("12"))

ggplot(plot_data, aes(x=time, y=Proportion, color=Compartment)) +
  geom_line() +
  geom_text_repel(data=plot_labels, aes(label=Compartment), direction="y", nudge_x=5, max.overlaps=1e6) +
  facet_wrap(vars(Var), scales="free_y") +
  theme(legend.position = "none") +
  labs(subtitle = "Begin with long-relapse hypnozoites, normal latent relapse, and complete treatment")
```

```{r scenario_4}
# Examine effect of the number of dormant stages
n_times = 365*5
ts = 1:n_times
cases = rpois(n_times, 100)
data = data_init(data_null,
                 n_times = n_times,
                 ts = ts,
                 cases = cases,
                 alpha = 0.5,
                 eps = 0,
                 p_long = 1,
                 gamma_l = 0,
                 gamma_d = 0)
data_1 = data_2 = data_3 = data
data_1$n_dormant = 1
data_1$y0 = state_init(data_1, I0 = 0.01)
data_2$n_dormant = 11
data_2$y0 = state_init(data_2, I0 = 0.01)
data_3$n_dormant = 50
data_3$y0 = state_init(data_3, I0 = 0.01)
real_params = list(lambda = 0.04)

sims_out = list(
  `n_dormant=1` = data_1,
  `n_dormant=11` = data_2,
  `n_dormant=50` = data_3
) %>%
  lapply(function(x) {
    my_simulate_data_list(
      file = model_file,
      data_name = "dummy_data",
      input_data = x,
      param_values = real_params,
      vars = c("y")
    )$y %>%
      as_tibble() %>%
      setNames(names(x$y0)) %>%
      mutate(time = x$ts, .before=0) %>%
      mutate(time = time,
             Infectious = rowSums(across(starts_with("I"))),
             Dormant = rowSums(across(matches(paste0("^Sc?l(", paste(seq_len(x$n_dormant), collapse="|"), ")$")))),
             Latent = rowSums(across(matches(paste0("^Sc?l", x$n_dormant+1, "$")))),
             Susceptible = S0,
             Prevalence = 1 - S0,
             Total = rowSums(across(matches(paste0("^(S|I).{,5}$")))),
             # Below incidence rates are in units of people per day
             across(matches("True"), ~ (lead(.x) - .x) / as.numeric(lead(time) - time)),
             TrueCases = TrueShortIncubations + TrueLongIncubations + TrueRelapses,
             ReportedShortIncubations = TrueShortIncubations * x$alpha,
             ReportedLongIncubations = TrueLongIncubations * x$alpha,
             ReportedRelapses = TrueRelapses * (1-x$relapse_clinical_immunity) * x$alpha,
             ReportedCases = ReportedShortIncubations + ReportedLongIncubations + ReportedRelapses,
             .keep = "used")
  })

plot_data = sims_out %>%
  bind_rows(.id = "Var") %>%
  mutate(Var = fct_inorder(Var)) %>%
  pivot_longer(c(ReportedCases, Infectious, Dormant, Latent, Susceptible, Total)) %>%
  mutate(Type = ifelse(name %in% c("ReportedCases", "Omega"), name, "Compartment"))

ggplot(plot_data, aes(x=time, y=value, color=name, linetype=Var)) +
  geom_line() +
  facet_grid(rows=vars(Type), scales="free_y") +
  labs("More dormant stages (more 'exact' timing) leads to peaky manifestation of seasonality")
```